ADD: compareSpeeds
santosfamilyfoundation/SantosGUI pull request #103
Opened 2017-04-23 20:26 UTC by youralien

Client side code for this cloud PR
https://github.com/santosfamilyfoundation/SantosCloud/pull/99

2017-04-25 17:52 UTC, dcelik requested changes
This should not be merged until #102 has been merged and the errors commented on below are addressed to match the design decisions in #102.

2017-04-25 17:52 UTC, dcelik commented on application/test_cloud.py
> +    remote.compareSpeeds(identifier, [identifier, identifier2], ['label1', 'label2'], project_path, False)
Do we want to put this in an "if identifier2:" or will the server/cloud_api handle it?

2017-04-25 17:52 UTC, dcelik commented on application/cloud_api.py
> +            return (False, 'Connection to server "{}" is offline'.format(self.server_addr))
Due to changes made in #102 , this will always need to be a 3-tuple. Once that is merged, your PR needs to be updated to reflect this.

2017-04-25 17:52 UTC, dcelik commented on application/cloud_api.py
> +            return (success, err)
Same here, parse_error will return a 3-tuple and the return will also need to be a 3-tuple.

2017-04-25 17:52 UTC, dcelik commented on application/cloud_api.py
> +        return (True, None)
Return 3-tuple here.

2017-04-25 17:52 UTC, dcelik commented on application/cloud_api.py
> +                    f.write(chunk)
This if exits and writing code also is encompassed in a helper function added in #102 . After that merge, please change this to reflect that addition.

2017-04-25 18:20 UTC, segerphilip reviewed
Agree with @dcelik comments, otherwise looks good

2017-04-26 15:30 UTC, youralien commented on application/test_cloud.py
> +    remote.compareSpeeds(identifier, [identifier, identifier2], ['label1', 'label2'], project_path, False)
Upcoming commits will handle and raise a 400 user error.

2017-04-26 18:31 UTC, youralien commented
@dcelik One more review please?

2017-04-26 18:43 UTC, dcelik approved these changes

2017-04-26 19:02 UTC, merged