Add turning counts routes
santosfamilyfoundation/SantosGUI pull request #104
Opened 2017-04-25 19:32 UTC by runnersaw

Adds turning counts routes to cloud_api. Should go in with [this SantosCloud PR](https://github.com/santosfamilyfoundation/SantosCloud/pull/101).

2017-04-25 19:55 UTC, dcelik requested changes
Make changes to match changes in #102. Other than that looks good. A rebase off of new dev could fix this.

2017-04-25 19:55 UTC, dcelik commented on application/cloud_api.py
> +            return (s, err)
Same here.

2017-04-25 19:55 UTC, dcelik commented on application/cloud_api.py
> +            return (True, None)
This should be a 3-tuple. See #102.

2017-04-25 19:55 UTC, dcelik commented on application/cloud_api.py
> +                    f.write(chunk)
Use the write_to_path helper function. See #102

2017-04-26 15:33 UTC, dcelik approved these changes

2017-04-26 17:03 UTC, merged

2017-04-26 17:04 UTC, runnersaw commented
Also includes using `pathos` multiprocess rather than multiprocessing in order to fix Windows issues. Appears to speed up download and video rendering on all platforms!