GUI gets default config from server
santosfamilyfoundation/SantosGUI pull request #34
Opened 2017-02-09 18:47 UTC by runnersaw

2017-02-09 18:49 UTC, jabb1123 approved these changes

2017-02-09 18:51 UTC, youralien approved these changes
:package:  and :rocket:

2017-02-09 19:23 UTC, dcelik requested changes

2017-02-09 19:23 UTC, dcelik commented on application/app.py
>                       max_segmentation_distance = mm_segmentation_distance)
This needs to be changed to max_segmentation_distance

2017-02-10 20:05 UTC, dcelik approved these changes

2017-02-10 20:09 UTC, merged