Removed identifier passing from uploadVideo()
santosfamilyfoundation/SantosGUI pull request #72
Opened 2017-02-26 19:54 UTC by dcelik

This PR removes the identifier argument from uploadVideo as that functionality is no longer supported. See our [SantosCloud PR](https://github.com/santosfamilyfoundation/SantosCloud/pull/69) for the accompanying server side fix.

2017-02-26 20:33 UTC, jabb1123 submitted a review, later dismissed

2017-02-26 20:36 UTC, youralien submitted a review, later dismissed

2017-02-26 22:40 UTC, dcelik commented
I added another functionality addition that decides to stream the data if it is over 100MB instead of loading it into memory and then sending it. The PR should be re-reviewed before merging.

2017-02-27 00:19 UTC, youralien requested changes

2017-02-27 00:19 UTC, youralien commented on application/cloud_api.py
> +            if m.len/(2**20) >= 100:
I don't understand the math here on first glance. Comment what units m.len is.  Why 2^20?

2017-02-27 00:19 UTC, youralien commented on application/cloud_api.py
> +from requests_toolbelt import MultipartEncoder
you should rebase dev (now that Qt5 branch is merged) and add requests_toolbelt to the install scripts

2017-02-27 00:42 UTC, youralien commented on application/cloud_api.py
> +            if m.len/(2**20) >= 100:
Now that I have read your cloud code, I'd prefer seeing the 1024*1024 for MB and then see  something in the comment like `1024*1024 bytes in a MB.`

2017-02-27 16:50 UTC, dcelik commented on application/cloud_api.py
> +from requests_toolbelt import MultipartEncoder
Sounds good, ill get on that.

2017-02-27 16:51 UTC, dcelik commented on application/cloud_api.py
> +            if m.len/(2**20) >= 100:
Okay, I will revise my comment and math to make it clearer

2017-02-27 17:01 UTC, youralien commented
PR's look ugly with all those commits :(

Can't you rebase on dev?

2017-02-27 17:14 UTC, dcelik commented
I tried to rebase on dev :(

2017-02-27 17:22 UTC, youralien commented
I used a force push and now it looks clean

2017-02-27 17:23 UTC, youralien approved these changes

2017-02-27 17:24 UTC, dcelik commented
Thank you!

2017-02-27 17:24 UTC, merged