Allows for building of Executable by running the SantosBuild script.
santosfamilyfoundation/SantosGUI pull request #73
Opened 2017-02-26 20:30 UTC by jabb1123

Big changes to Note:
 - Project path is now under user's `Document/TrafficAnalysis/`
 - Fonts stored in `/application/datas/fonts/`
    - These are pulled during package build. Added to `app.spec` file
    - Any new resource that is non-python, non-binary needs to be added to the datas list in `app.spec`

2017-02-26 20:42 UTC, youralien requested changes

2017-02-26 20:42 UTC, youralien commented on application/app_config.py
> +    PROJECT_DIR = os.path.realpath(os.path.join(os.path.expanduser('~'),"Documents" , "TrafficAnalysis", "project_dir"))
This is a huge change to how things work on my system.  Currently, my project_dir is stored at 

{path_to_gui_folder}/SantosGUI/project_gui

This change makes it ~/Documents/TrafficAnalysis/project_dir, which is not a folder I have on my Mac setup

2017-02-26 20:42 UTC, youralien commented on requirements.txt
> +Image==1.5.5
I don't think we need this requirements.txt file.  I removed it previously because we are now depending on the install_conda_deps.sh

2017-02-26 22:42 UTC, dcelik requested changes

2017-02-26 22:42 UTC, dcelik commented on application/SantosBuild
> +pyinstaller --debug $DIR/app.spec
Have --debug flag be taken as a parameter for the script instead of a hardcoded.

2017-02-26 22:42 UTC, dcelik commented on application/app.spec
> +print os.getcwd()
Why are you printing this? Remove if you are done testing.

2017-02-26 22:42 UTC, dcelik commented on application/app_config.py
> +    PROJECT_DIR = os.path.realpath(os.path.join(os.path.expanduser('~'),"Documents" , "TrafficAnalysis", "project_dir"))
Lets make the folder name the same as the Application.

2017-02-26 22:42 UTC, dcelik commented on requirements.txt
> +Image==1.5.5
+1 lets make sure we aren't duplicating previous changes on dev!

2017-02-27 15:56 UTC, jabb1123 commented on application/app_config.py
> +    PROJECT_DIR = os.path.realpath(os.path.join(os.path.expanduser('~'),"Documents" , "TrafficAnalysis", "project_dir"))
I'll make the Application name a variable for now, until we settle on a finalized name. I'll set it as SantosGUI now. Note other code will create the directory in the process of creating a project. In addition, opening another project overwrites this path, so it should be possible to load old projects from any directory.

2017-02-27 16:23 UTC, youralien approved these changes

2017-02-27 16:50 UTC, dcelik requested changes
I think that SantosBuild should take some sort of debug flag so we can debug it easily.

2017-02-27 18:06 UTC, dcelik requested changes

2017-02-27 18:06 UTC, dcelik commented on install_conda_deps.sh
> +conda remove -n $YOURENVNAME mkl mkl-service
Lets do each of these on their own line with a version number. Also why do we remove mkl from conda? Is it possible to just suppress it from being added instead?

2017-02-28 18:49 UTC, jabb1123 commented on install_conda_deps.sh
> +conda remove -n $YOURENVNAME mkl mkl-service
Its included in base installations of both miniconda and anaconda. It has to be removed, nad by versioning, the user can still have their default install with these optimizations.

2017-02-28 23:10 UTC, dcelik commented on install_conda_deps.sh
> +conda remove -n $YOURENVNAME mkl mkl-service
Sounds good, what about numpy, scipy and scikit-learn having their own version numbers? If nothing else we should at least specify a major version number so we don't have unexpected functionality changes in the futur.

2017-03-01 14:28 UTC, runnersaw requested changes
Hi

2017-03-01 14:28 UTC, runnersaw commented on application/packaging/SantosBuild
>  pyinstaller $DIR/app.spec
This isn't the same as SantosBuild.sh

2017-03-01 16:06 UTC, dcelik requested changes

2017-03-01 16:06 UTC, dcelik commented on application/dist/build_settings.py
>  # .. Useful stuff ..............................................................
Try this instead:
```
################################################################################
# Useful stuff
################################################################################
```

2017-03-01 16:07 UTC, dcelik commented
Still waiting on versions btw!

2017-03-01 17:27 UTC, dcelik commented
Looks good! Ship it.

2017-03-01 17:27 UTC, dcelik approved these changes

2017-03-01 18:43 UTC, runnersaw approved these changes
:ship: it

2017-03-01 18:51 UTC, merged