Improve README and install instructions
santosfamilyfoundation/SantosGUI pull request #93
Opened 2017-04-07 20:23 UTC by runnersaw

1. Improved README
2. Improved install (move to using only environment.yml file, with OS detection to use the correct yml file)
3. Remove cv2 from all code. Use PIL.Image or ffmpeg if needed.

2017-04-07 20:26 UTC, jabb1123 approved these changes
Looks awesome. Good to remove OpenCV from GUI too!

2017-04-07 20:31 UTC, dcelik requested changes
Looks go to me!

2017-04-07 20:31 UTC, dcelik commented on application/app.py
> +        success, err = api.configHomography(\
wat.

2017-04-07 20:31 UTC, dcelik commented on application/app.py
> +            videoDraw.text((x, y), str(i+1), fill=cvBlue)
I think differentiating the text color would be useful. White text with a black stroke is visible on anything.

2017-04-09 18:05 UTC, dcelik approved these changes
Very interesting way of creating circles and texts! LGTM

2017-04-09 18:06 UTC, merged